# -*- coding: utf-8 -*-
"""Prodigy Task4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tg1X19RiAt_BITmrTYtMI1Xf_xhV_f69
"""

from google.colab import files
files.upload()

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

!kaggle datasets list -s leapgestrecog

!kaggle datasets download -d gti-upm/leapgestrecog

!unzip -q leapgestrecog.zip

import os

print(os.listdir("leapGestRecog")[:5])

!pip install tensorflow opencv-python

import os
import cv2
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D
from tensorflow.keras.layers import Flatten, Dense, Dropout

dataset_path = "leapGestRecog"

images = []
labels = []

IMG_SIZE = 64

count = 0
MAX_IMAGES = 5000

for person in os.listdir(dataset_path):

    person_path = os.path.join(dataset_path, person)

    if not os.path.isdir(person_path):
        continue

    for gesture in os.listdir(person_path):

        gesture_path = os.path.join(person_path, gesture)

        for img_name in os.listdir(gesture_path):

            img_path = os.path.join(
                gesture_path,
                img_name
            )

            img = cv2.imread(
                img_path,
                cv2.IMREAD_GRAYSCALE
            )

            img = cv2.resize(
                img,
                (IMG_SIZE, IMG_SIZE)
            )

            images.append(img)
            labels.append(gesture)

            count += 1

            if count >= MAX_IMAGES:
                break

        if count >= MAX_IMAGES:
            break

    if count >= MAX_IMAGES:
        break

print("Loaded:", len(images))

X = np.array(images)

X = X / 255.0

X = X.reshape(
    X.shape[0],
    IMG_SIZE,
    IMG_SIZE,
    1
)

X = np.array(images)

X = X / 255.0

X = X.reshape(
    X.shape[0],
    IMG_SIZE,
    IMG_SIZE,
    1
)

encoder = LabelEncoder()

y = encoder.fit_transform(labels)

y = to_categorical(y)

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

model = Sequential()

model.add(
    Conv2D(
        32,
        (3,3),
        activation='relu',
        input_shape=(64,64,1)
    )
)

model.add(
    MaxPooling2D((2,2))
)

model.add(
    Conv2D(
        64,
        (3,3),
        activation='relu'
    )
)

model.add(
    MaxPooling2D((2,2))
)

model.add(
    Flatten()
)

model.add(
    Dense(
        128,
        activation='relu'
    )
)

model.add(
    Dropout(0.3)
)

model.add(
    Dense(
        y.shape[1],
        activation='softmax'
    )
)

model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

history = model.fit(
    X_train,
    y_train,
    validation_data=(X_test, y_test),
    epochs=10,
    batch_size=32
)

loss, accuracy = model.evaluate(
    X_test,
    y_test
)

print("Accuracy:", accuracy)

plt.figure(figsize=(8,5))

plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])

plt.legend([
    "Train",
    "Validation"
])

plt.title("Accuracy")

plt.show()

model.save("gesture_model.h5")

MAX_IMAGES = 10000